export const LANGUAGE_OPTIONS = [
  { label: "Plain Text",      value: "plaintext"   },
  { label: "Bash / Shell",    value: "shell"        },
  { label: "C",               value: "c"            },
  { label: "C++",             value: "cpp"          },
  { label: "C#",              value: "csharp"       },
  { label: "CSS",             value: "css"          },
  { label: "Dockerfile",      value: "dockerfile"   },
  { label: "Go",              value: "go"           },
  { label: "GraphQL",         value: "graphql"      },
  { label: "HTML",            value: "html"         },
  { label: "Java",            value: "java"         },
  { label: "JavaScript",      value: "javascript"   },
  { label: "JSON",            value: "json"         },
  { label: "Kotlin",          value: "kotlin"       },
  { label: "Markdown",        value: "markdown"     },
  { label: "PHP",             value: "php"          },
  { label: "Python",          value: "python"       },
  { label: "Ruby",            value: "ruby"         },
  { label: "Rust",            value: "rust"         },
  { label: "SQL",             value: "sql"          },
  { label: "Swift",           value: "swift"        },
  { label: "Terraform / HCL", value: "hcl"          },
  { label: "TypeScript",      value: "typescript"   },
  { label: "XML",             value: "xml"          },
  { label: "YAML",            value: "yaml"         },
] as const
